// src/App.vue
<template>
  <div class="vpw-fm-launcher-root" :class="themeClass">
   
      <button
        class="vpw-open-fm-btn"
        :class="{ 'vpw-is-active': showPanel, 'vpw-is-dragging': isDragging }"
        :style="launcherStyle"
        :data-tip="launcherTip"
        :aria-pressed="showPanel"
        @click="togglePanel"
        @keydown.space.prevent="togglePanel"
        @keydown.enter.prevent="togglePanel"
        @pointerdown="onLauncherPointerDown"
        :aria-expanded="showPanel"
        aria-controls="file-manager-panel"
        :aria-label="launcherTip"
        :title="launcherTip"
      >
        <img :src="logo" alt="" class="logo" />
        <span class="vpw-visually-hidden">{{ launcherTip }}</span>
      </button>

      <!-- Theme Toggle Button >
      <button
        class="vpw-theme-toggle-btn"
        @click="toggleTheme"
        :title="currentTheme === 'light' ? '切换到深色模式' : '切换到浅色模式'"
        aria-label="切换主题"
      >
        <svg v-if="currentTheme === 'light'" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path>
        </svg>
        <svg v-else width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <circle cx="12" cy="12" r="5"></circle>
          <line x1="12" y1="1" x2="12" y2="3"></line>
          <line x1="12" y1="21" x2="12" y2="23"></line>
          <line x1="4.22" y1="4.22" x2="5.64" y2="5.64"></line>
          <line x1="18.36" y1="18.36" x2="19.78" y2="19.78"></line>
          <line x1="1" y1="12" x2="3" y2="12"></line>
          <line x1="21" y1="12" x2="23" y2="12"></line>
          <line x1="4.22" y1="19.78" x2="5.64" y2="18.36"></line>
          <line x1="18.36" y1="5.64" x2="19.78" y2="4.22"></line>
        </svg>
      </button-->

    <!-- 挂载主窗体组件 -->
    <FileManagerPanel
      id="file-manager-panel"
      :visible="showPanel"
      @close="closePanel"
    />
  </div>
</template>

<script setup>
import { ref, computed, onMounted, onBeforeUnmount } from 'vue'
import { useTheme, provideTheme } from './services/ThemeService'
import FileManagerPanel from './components/FileManagerPanel.vue'
import { hostWindow } from './utils/host-window.js'
import logo from './assets/logo.png'

const showPanel = ref(false)
const isMobile = ref(false)
const isDragging = ref(false)
const launcherX = ref(20)
const launcherY = ref(100)
const launcherSize = ref(64)
const hasCustomLauncherPosition = ref(false)
const suppressNextToggle = ref(false)
const MOBILE_BREAKPOINT = 640
const LAUNCHER_STORAGE_KEY = 'vpw-launcher-position-v1'

let pointerId = null
let dragStartX = 0
let dragStartY = 0
let buttonStartX = 0
let buttonStartY = 0
let hasMovedBeyondClickThreshold = false

// Initialize theme
const theme = useTheme()
const { initTheme, themeClass: getThemeClass, toggleTheme, currentTheme } = theme
const themeClass = computed(() => getThemeClass())

// Provide theme context to all descendants
provideTheme(theme)

function updateIsMobile() {
  isMobile.value = hostWindow.innerWidth < MOBILE_BREAKPOINT
}

function onWindowResize() {
  updateIsMobile()
  syncLauncherLayout()
}

const launcherTip = computed(() => (showPanel.value ? '关闭文件管理器' : '打开文件管理器'))

const launcherStyle = computed(() => ({
  left: `${launcherX.value}px`,
  top: `${launcherY.value}px`,
  width: `${launcherSize.value}px`,
  height: `${launcherSize.value}px`
}))

function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value))
}

function getLauncherBounds(size = launcherSize.value) {
  const margin = 12
  const maxX = Math.max(margin, hostWindow.innerWidth - size - margin)
  const maxY = Math.max(margin, hostWindow.innerHeight - size - margin)

  return {
    minX: margin,
    maxX,
    minY: margin,
    maxY
  }
}

function getAdaptiveLauncherSize() {
  const shortEdge = Math.min(hostWindow.innerWidth, hostWindow.innerHeight)
  return clamp(Math.round(shortEdge * 0.09), 52, 72)
}

function getDefaultLauncherPosition(size = launcherSize.value) {
  const { minX, maxX, maxY } = getLauncherBounds(size)
  const defaultX = isMobile.value
    ? Math.round((hostWindow.innerWidth - size) / 2)
    : minX + 8
  const defaultY = maxY - (isMobile.value ? 8 : 72)

  return {
    x: clamp(defaultX, minX, maxX),
    y: clamp(defaultY, 12, maxY)
  }
}

function saveLauncherPosition() {
  try {
    hostWindow.localStorage.setItem(
      LAUNCHER_STORAGE_KEY,
      JSON.stringify({ x: launcherX.value, y: launcherY.value })
    )
  } catch {
    // Ignore storage failures in restricted environments
  }
}

function loadLauncherPosition() {
  try {
    const raw = hostWindow.localStorage.getItem(LAUNCHER_STORAGE_KEY)
    if (!raw) return

    const parsed = JSON.parse(raw)
    if (typeof parsed?.x === 'number' && typeof parsed?.y === 'number') {
      launcherX.value = parsed.x
      launcherY.value = parsed.y
      hasCustomLauncherPosition.value = true
    }
  } catch {
    // Ignore malformed storage data
  }
}

function syncLauncherLayout() {
  launcherSize.value = getAdaptiveLauncherSize()

  if (!hasCustomLauncherPosition.value) {
    const { x, y } = getDefaultLauncherPosition(launcherSize.value)
    launcherX.value = x
    launcherY.value = y
    return
  }

  const { minX, maxX, minY, maxY } = getLauncherBounds(launcherSize.value)
  launcherX.value = clamp(launcherX.value, minX, maxX)
  launcherY.value = clamp(launcherY.value, minY, maxY)
}

function onLauncherPointerDown(event) {
  if (event.button !== 0) return

  pointerId = event.pointerId
  isDragging.value = true
  hasMovedBeyondClickThreshold = false
  dragStartX = event.clientX
  dragStartY = event.clientY
  buttonStartX = launcherX.value
  buttonStartY = launcherY.value

  event.currentTarget?.setPointerCapture?.(pointerId)
  hostWindow.addEventListener('pointermove', onLauncherPointerMove)
  hostWindow.addEventListener('pointerup', onLauncherPointerUp)
  hostWindow.addEventListener('pointercancel', onLauncherPointerUp)
}

function onLauncherPointerMove(event) {
  if (!isDragging.value || event.pointerId !== pointerId) return

  const deltaX = event.clientX - dragStartX
  const deltaY = event.clientY - dragStartY
  const movedDistance = Math.hypot(deltaX, deltaY)
  if (movedDistance > 6) {
    hasMovedBeyondClickThreshold = true
  }

  const { minX, maxX, minY, maxY } = getLauncherBounds(launcherSize.value)
  launcherX.value = clamp(buttonStartX + deltaX, minX, maxX)
  launcherY.value = clamp(buttonStartY + deltaY, minY, maxY)
}

function onLauncherPointerUp(event) {
  if (!isDragging.value || event.pointerId !== pointerId) return

  isDragging.value = false
  pointerId = null
  hostWindow.removeEventListener('pointermove', onLauncherPointerMove)
  hostWindow.removeEventListener('pointerup', onLauncherPointerUp)
  hostWindow.removeEventListener('pointercancel', onLauncherPointerUp)

  if (hasMovedBeyondClickThreshold) {
    suppressNextToggle.value = true
    hasCustomLauncherPosition.value = true
    saveLauncherPosition()
  }
}

onMounted(() => {
  initTheme()
  updateIsMobile()
  loadLauncherPosition()
  syncLauncherLayout()
  hostWindow.addEventListener('resize', onWindowResize)
})

onBeforeUnmount(() => {
  hostWindow.removeEventListener('pointermove', onLauncherPointerMove)
  hostWindow.removeEventListener('pointerup', onLauncherPointerUp)
  hostWindow.removeEventListener('pointercancel', onLauncherPointerUp)
  hostWindow.removeEventListener('resize', onWindowResize)
})

function togglePanel() {
  if (suppressNextToggle.value) {
    suppressNextToggle.value = false
    return
  }

  showPanel.value = !showPanel.value
}

function closePanel() {
  showPanel.value = false
}
</script>

<style scoped>
/* 根容器保持简单，避免创建 stacking context */
.vpw-fm-launcher-root {
  width: 100%;
  position: relative;
}

/* top bar 用于布局（如果未来需要扩展可修改） */
.vpw-top-bar {
  padding: 14px 20px;
}

/* 圆形悬浮按钮主样式 */
.vpw-open-fm-btn {
  position: fixed;
  left: 20px;
  top: 100px;

  width: 64px;
  height: 64px;
  min-width: 56px;
  min-height: 56px;
  padding: 0;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  border: none;
  cursor: pointer;
  background: linear-gradient(135deg, #ffffff 0%, #cfcfcf 55%, #e5e5e5 100%);
  color: #07213a;

  box-shadow:
    0 10px 30px rgba(7, 33, 58, 0.18),
    inset 0 1px 0 rgba(255,255,255,0.35);
  z-index: 2147483647;

  transition: transform 180ms cubic-bezier(.2,.9,.2,1), box-shadow 180ms, filter 180ms, background 180ms;
  -webkit-tap-highlight-color: transparent;
  touch-action: none;
  pointer-events: auto;
  outline: none;
}

.vpw-open-fm-btn.vpw-is-active {
  background: linear-gradient(135deg, #ffffff 0%, #c8d6e8 55%, #d8e6f7 100%);
  box-shadow:
    0 14px 36px rgba(7, 33, 58, 0.28),
    inset 0 1px 0 rgba(255,255,255,0.45);
}

.vpw-open-fm-btn.vpw-is-dragging {
  cursor: grabbing;
  transition: none;
  box-shadow:
    0 8px 24px rgba(7, 33, 58, 0.26),
    inset 0 1px 0 rgba(255,255,255,0.28);
}

/* 内部 logo，使用相对导入的图片资源 */
.vpw-open-fm-btn .logo {
  width: 56%;
  height: 56%;
  object-fit: contain;
  display: block;
  border-radius: 50%;
  filter: drop-shadow(0 3px 8px rgba(7,33,58,0.14));
}

/* Hover/active 状态以增强交互感知 */
@media (hover: hover) and (pointer: fine) {
  .vpw-open-fm-btn:hover {
    transform: translateY(-6px);
    box-shadow:
      0 18px 42px rgba(7, 33, 58, 0.26),
      inset 0 1px 0 rgba(255,255,255,0.38);
    filter: saturate(1.05);
  }
}

.vpw-open-fm-btn:active {
  transform: translateY(-2px) scale(0.985);
  box-shadow:
    0 8px 20px rgba(7, 33, 58, 0.18),
    inset 0 1px 0 rgba(255,255,255,0.25);
}

/* Focus-visible 优化，便于键盘用户 */
.vpw-open-fm-btn:focus-visible {
  box-shadow:
    0 12px 36px rgba(7,33,58,0.22),
    0 0 0 6px rgba(95, 180, 255, 0.18);
  outline: none;
}

/* 简洁的 tooltip（桌面设备） */
.vpw-open-fm-btn::after {
  content: attr(data-tip);
  position: absolute;
  left: calc(100% + 12px);
  bottom: 50%;
  transform: translateY(50%) translateX(0);
  background: rgba(8, 20, 34, 0.95);
  color: #fff;
  padding: 6px 10px;
  border-radius: 8px;
  font-size: 13px;
  white-space: nowrap;
  opacity: 0;
  pointer-events: none;
  transition: opacity 160ms, transform 160ms;
  box-shadow: 0 8px 28px rgba(8, 20, 34, 0.32);
  z-index: 2147483647;
}

@media (prefers-reduced-motion: reduce) {
  .vpw-open-fm-btn,
  .vpw-open-fm-btn::after,
  .vpw-open-fm-btn::before {
    transition: none;
  }

  .vpw-open-fm-btn:hover,
  .vpw-open-fm-btn:active {
    transform: none;
  }
}

.vpw-open-fm-btn::before {
  content: "";
  position: absolute;
  left: calc(100% + 6px);
  bottom: 50%;
  transform: translateY(50%) rotate(45deg);
  width: 10px;
  height: 10px;
  background: rgba(8, 20, 34, 0.95);
  opacity: 0;
  transition: opacity 160ms;
  z-index: 2147483647;
}

@media (hover: hover) and (pointer: fine) {
  .vpw-open-fm-btn:hover::after,
  .vpw-open-fm-btn:focus-visible::after {
    opacity: 1;
    transform: translateY(50%) translateX(6px);
  }
  .vpw-open-fm-btn:hover::before,
  .vpw-open-fm-btn:focus-visible::before {
    opacity: 1;
    transform: translateY(50%) rotate(45deg) translateX(4px);
  }
}

/* 小屏或触摸设备上隐藏 tooltip */
@media (max-width: 480px) {
  .vpw-open-fm-btn::after,
  .vpw-open-fm-btn::before {
    display: none;
  }
}

/* 屏幕阅读器隐藏文本 */
.vpw-visually-hidden {
  position: absolute !important;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0 0 0 0);
  white-space: nowrap;
  border: 0;
}

/* Theme toggle button */
.vpw-theme-toggle-btn {
  position: fixed;
  left: calc(var(--safe-area-left) + clamp(16px, 3vw, 20px));
  bottom: calc(var(--safe-area-bottom) + clamp(20px, 4vh, 30px));
  width: clamp(44px, 10vw, 48px);
  height: clamp(44px, 10vw, 48px);
  min-width: 44px;
  min-height: 44px;
  padding: 0;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border-radius: var(--radius-round, 50%);
  border: none;
  cursor: pointer;
  background: var(--color-bg-surface, #ffffff);
  color: var(--color-text-primary, #07213a);
  box-shadow: var(--shadow-lg, 0 6px 20px rgba(7, 33, 58, 0.16));
  z-index: 2147483647;
  transition: transform 180ms cubic-bezier(.2,.9,.2,1), box-shadow var(--transition-base, 180ms), filter var(--transition-base, 180ms);
  -webkit-tap-highlight-color: transparent;
  touch-action: manipulation;
  pointer-events: auto;
  outline: none;
}

/* Mobile: position theme toggle near launcher */
@media (max-width: 640px) {
  .vpw-theme-toggle-btn {
    left: calc(50% + 48px);
    bottom: calc(var(--safe-area-bottom) + 24px);
  }
}

@media (hover: hover) and (pointer: fine) {
  .vpw-theme-toggle-btn:hover {
    transform: translateY(-4px) scale(1.05);
    box-shadow: var(--shadow-xl, 0 12px 28px rgba(7, 33, 58, 0.22));
    filter: saturate(1.05);
  }
}

.vpw-theme-toggle-btn:active {
  transform: translateY(-1px) scale(0.98);
  box-shadow: var(--shadow-md, 0 4px 12px rgba(7, 33, 58, 0.16));
}

.vpw-theme-toggle-btn:focus-visible {
  box-shadow:
    var(--shadow-lg, 0 8px 24px rgba(7,33,58,0.18)),
    0 0 0 4px rgba(95, 180, 255, 0.18);
  outline: none;
}
</style>

// src/ui/App.tsx
import { useCallback, useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react'
import { hostWindow } from '@/utils/host-window.js'
import logo from '@/assets/logo.png'
import { FileManagerPanel } from './components/FileManagerPanel'

interface AppProps {
  rootEl: HTMLElement
}

const LAUNCHER_STORAGE_KEY = 'vpw-launcher-position-v1'
const DRAG_THRESHOLD = 6
const LAUNCHER_MIN_SIZE = 44
const LAUNCHER_MAX_SIZE = 104

function clamp(value: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, value))
}

/** Root wardrobe UI: a draggable floating launcher that toggles the main panel. */
export function App(_props: AppProps) {
  const [showPanel, setShowPanel] = useState(false)
  const [pos, setPos] = useState({ x: 20, y: 100 })
  const [size, setSize] = useState(64)
  const [dragging, setDragging] = useState(false)
  const [resizing, setResizing] = useState(false)

  const drag = useRef({ active: false, startX: 0, startY: 0, baseX: 0, baseY: 0, moved: false })
  const resize = useRef({ active: false, startX: 0, baseSize: 64, moved: false })
  const latestSize = useRef(size)
  const suppressClick = useRef(false)
  const hasCustomPos = useRef(false)
  const hasCustomSize = useRef(false)

  const adaptiveSize = useCallback(() => {
    const shortEdge = Math.min(hostWindow.innerWidth, hostWindow.innerHeight)
    return clamp(Math.round(shortEdge * 0.09), 52, 72)
  }, [])

  useEffect(() => {
    latestSize.current = size
  }, [size])

  const bounds = useCallback((s: number) => {
    const margin = 12
    return {
      minX: margin,
      maxX: Math.max(margin, hostWindow.innerWidth - s - margin),
      minY: margin,
      maxY: Math.max(margin, hostWindow.innerHeight - s - margin),
    }
  }, [])

  // Load persisted position once.
  useEffect(() => {
    let loadedSize: number | null = null
    try {
      const raw = hostWindow.localStorage.getItem(LAUNCHER_STORAGE_KEY)
      if (raw) {
        const parsed = JSON.parse(raw)
        if (typeof parsed?.x === 'number' && typeof parsed?.y === 'number') {
          setPos({ x: parsed.x, y: parsed.y })
          hasCustomPos.current = true
        }
        if (typeof parsed?.size === 'number') {
          loadedSize = clamp(parsed.size, LAUNCHER_MIN_SIZE, LAUNCHER_MAX_SIZE)
          setSize(loadedSize)
          hasCustomSize.current = true
        }
      }
    } catch {
      /* ignore */
    }
    const s = loadedSize ?? adaptiveSize()
    setSize(s)
    if (!hasCustomPos.current) {
      const b = bounds(s)
      setPos({ x: b.minX + 8, y: b.maxY - 72 })
    }
  }, [adaptiveSize, bounds])

  // Keep launcher inside the viewport on resize.
  useEffect(() => {
    const onResize = () => {
      const s = hasCustomSize.current ? size : adaptiveSize()
      setSize(s)
      setPos((p) => {
        if (!hasCustomPos.current) {
          const b = bounds(s)
          return { x: b.minX + 8, y: b.maxY - 72 }
        }
        const b = bounds(s)
        return { x: clamp(p.x, b.minX, b.maxX), y: clamp(p.y, b.minY, b.maxY) }
      })
    }
    hostWindow.addEventListener('resize', onResize)
    return () => hostWindow.removeEventListener('resize', onResize)
  }, [adaptiveSize, bounds, size])

  const onPointerMove = useCallback(
    (event: globalThis.PointerEvent) => {
      if (!drag.current.active) return
      const dx = event.clientX - drag.current.startX
      const dy = event.clientY - drag.current.startY
      if (Math.hypot(dx, dy) > DRAG_THRESHOLD) drag.current.moved = true
      const b = bounds(size)
      setPos({
        x: clamp(drag.current.baseX + dx, b.minX, b.maxX),
        y: clamp(drag.current.baseY + dy, b.minY, b.maxY),
      })
    },
    [bounds, size],
  )

  const onResizeMove = useCallback(
    (event: globalThis.PointerEvent) => {
      if (!resize.current.active) return
      const dx = event.clientX - resize.current.startX
      if (Math.abs(dx) > DRAG_THRESHOLD) resize.current.moved = true
      const maxFromViewport = Math.min(LAUNCHER_MAX_SIZE, hostWindow.innerWidth - pos.x - 12, hostWindow.innerHeight - pos.y - 12)
      setSize(clamp(resize.current.baseSize + dx, LAUNCHER_MIN_SIZE, Math.max(LAUNCHER_MIN_SIZE, maxFromViewport)))
    },
    [pos.x, pos.y],
  )

  const onPointerUp = useCallback(() => {
    const wasDragging = drag.current.active
    const wasResizing = resize.current.active
    if (!wasDragging && !wasResizing) return
    drag.current.active = false
    resize.current.active = false
    setDragging(false)
    setResizing(false)
    hostWindow.removeEventListener('pointermove', onPointerMove)
    hostWindow.removeEventListener('pointermove', onResizeMove)
    hostWindow.removeEventListener('pointerup', onPointerUp)
    if (drag.current.moved || resize.current.moved) {
      suppressClick.current = true
      hasCustomPos.current = true
      if (resize.current.moved) hasCustomSize.current = true
      setPos((p) => {
        try {
          hostWindow.localStorage.setItem(LAUNCHER_STORAGE_KEY, JSON.stringify({ ...p, size: latestSize.current }))
        } catch {
          /* ignore */
        }
        return p
      })
    }
  }, [onPointerMove, onResizeMove, size])

  const onPointerDown = (event: ReactPointerEvent) => {
    if (event.button !== 0) return
    drag.current = {
      active: true,
      startX: event.clientX,
      startY: event.clientY,
      baseX: pos.x,
      baseY: pos.y,
      moved: false,
    }
    setDragging(true)
    hostWindow.addEventListener('pointermove', onPointerMove)
    hostWindow.addEventListener('pointerup', onPointerUp)
  }

  const onResizePointerDown = (event: ReactPointerEvent) => {
    if (event.button !== 0) return
    event.preventDefault()
    event.stopPropagation()
    resize.current = {
      active: true,
      startX: event.clientX,
      baseSize: size,
      moved: false,
    }
    setResizing(true)
    hostWindow.addEventListener('pointermove', onResizeMove)
    hostWindow.addEventListener('pointerup', onPointerUp)
  }

  const togglePanel = () => {
    if (suppressClick.current) {
      suppressClick.current = false
      return
    }
    setShowPanel((v) => !v)
  }

  return (
    <>
      <button
        type="button"
        onClick={togglePanel}
        onPointerDown={onPointerDown}
        aria-pressed={showPanel}
        title="Vivian's Portable Wardrobe"
        style={{
          position: 'fixed',
          left: pos.x,
          top: pos.y,
          width: size,
          height: size,
          borderRadius: '50%',
          border: 'none',
          padding: 0,
          cursor: dragging ? 'grabbing' : resizing ? 'nwse-resize' : 'pointer',
          background: 'linear-gradient(135deg, #ffffff 0%, #cfcfcf 55%, #e5e5e5 100%)',
          boxShadow: '0 10px 30px rgba(7, 33, 58, 0.18)',
          zIndex: 2147483647,
          touchAction: 'none',
          display: showPanel ? 'none' : 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          overflow: 'hidden',
        }}
      >
        <img src={logo} alt="" style={{ width: '56%', height: '56%', objectFit: 'contain', pointerEvents: 'none' }} />
        <span
          aria-hidden
          onPointerDown={onResizePointerDown}
          style={{
            position: 'absolute',
            right: 4,
            bottom: 4,
            width: Math.max(10, size * 0.18),
            height: Math.max(10, size * 0.18),
            borderRadius: '50%',
            background: 'rgba(20, 85, 140, 0.58)',
            border: '1px solid rgba(255,255,255,0.85)',
            cursor: 'nwse-resize',
            touchAction: 'none',
          }}
        />
      </button>

      <FileManagerPanel opened={showPanel} onClose={() => setShowPanel(false)} />
    </>
  )
}
